name: ci

on:
  schedule:
    # once a week build a new image
    - cron: '30 1 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
      -
        name: Get XOA version
        uses: actions/github-script@v4
        id: xoa_version
        with:
          result-encoding: string
          script: |
          const myurl = https://raw.githubusercontent.com/vatesfr/xen-orchestra/master/packages/xo-server/package.json
          const result = await github.request(myurl)
          console.log(result)
          return result.version
      -
        name: Debug
        run: echo ${{ steps.xoa_version.outputs.result }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./alpine
          push: false
          tags: ezka77/xen-orchestra-ce:latest
